! Number of depth points, number of models
      integer,parameter  :: ndp=100

! Opacities
      integer,parameter  :: mopac=600000,mopav=mopac/10+1
      integer,parameter  :: mmol=99,mmol1=mmol+1

! Number of wavelength points
      integer,parameter  :: nwl=149000

! Temperature columns in opacity file
      integer,parameter  :: mtemp=100

! Elements and species
      integer,parameter  :: natms=49,nions=127,nspec=896

